name: tech_interview_outcomes
version: '1.0.0'
config-version: 2

profile: tech_interview_outcomes

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tech_interview_outcomes:
    staging:
      +materialized: view
    marts:
      +materialized: table
